name: Unity Workflow Sample
on: [push]
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
       with:
         lfs: true

     - uses: webbertakken/unity-test-runner@v1.4
       with:
        unityVersion: 2018.4.19f1

     - uses: actions/upload-artifact@v1
       with:
        name: Test results
        path: artifacts